- name: Configure NGINX with Dynamic Configuration
  hosts: all
  become: yes

  tasks:
    - name: Ensure nginx directory exists
      file:
        path: /etc/nginx/conf.d
        state: directory

    - name: Copy the dynamic NGINX configuration
      template:
        src: app.conf.j2
        dest: /etc/nginx/conf.d/app.conf
        mode: '0644'

    - name: Test NGINX configuration
      command: nginx -t

    - name: Restart NGINX to apply changes
      systemd:
        name: nginx
        state: restarted

