---
- name: Install and configure Node Exporter
  become: true
  hosts: all

  tasks:
    - name: Create node_exporter user
      user:
        name: node_exporter
        shell: /sbin/nologin

    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move binary to /usr/local/bin
      command: mv /tmp/node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/node_exporter
      become: true
      args:
        creates: /usr/local/bin/node_exporter

    - name: Create Node Exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd and start Node Exporter
      systemd:
        daemon_reload: yes
        name: node_exporter
        enabled: yes
        state: started

